OPENAI_API_KEY = "xxxx"
AZURE_OPENAI_ENDPOINT = "https://xxx"

[connections.snowflake]
user = "xxx"
password = "xxx"
warehouse = "xxx"
role = "xxx"
# Find your account info here:
# https://docs.snowflake.com/en/user-guide/admin-account-identifier
account = "xxx"
